services:
  api:
    build: .
    container_name: flight_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/flights
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  worker:
    build: .
    command: python app/worker.py
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/flights
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
